### ISSUE TITLE
Question: VqsVulkanFunctions

### ISSUE THREAD

**Issue by ib00** [AdamYuan/VulkanQueueSelector#1]
I am using volk (https://github.com/zeux/volk) as a Vulkan loader.

When using your queue selector, I see that you need to specify 
appropriate functions in VqsVulkanFunctions. How does that play
with loaders like volk?

**Comment by AdamYuan** [comment]
Since volk simply loads vulkan functions to global function pointers,
```c++
VqsVulkanFunctions functions = {
    vkGetPhysicalDeviceQueueFamilyProperties,
    vkGetPhysicalDeviceSurfaceSupportKHR
};
```
could work.
